//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EasyBookingEntities : DbContext
    {
        public EasyBookingEntities()
            : base("name=EasyBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_BUSINESS> TBL_BUSINESS { get; set; }
        public virtual DbSet<TBL_CUST_ORDER> TBL_CUST_ORDER { get; set; }
        public virtual DbSet<TBL_CUSTOMER> TBL_CUSTOMER { get; set; }
        public virtual DbSet<TBL_DURATION_TYPE> TBL_DURATION_TYPE { get; set; }
        public virtual DbSet<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
        public virtual DbSet<TBL_LOCATION> TBL_LOCATION { get; set; }
        public virtual DbSet<TBL_PAYMENT> TBL_PAYMENT { get; set; }
        public virtual DbSet<TBL_SERVICE_CATEGORIES> TBL_SERVICE_CATEGORIES { get; set; }
        public virtual DbSet<TBL_SERVICES> TBL_SERVICES { get; set; }
        public virtual DbSet<X_SERVICE_EMPLOYEE> X_SERVICE_EMPLOYEE { get; set; }
        public virtual DbSet<X_SERVICE_LOCATION> X_SERVICE_LOCATION { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int USP_INSERT_BUSINESS(string bUSINESS_NAME, string bUSINESS_ADDRESS, string bUSINESS_TYPE, string rEG_NO, string oWNER_NAME, Nullable<int> lOCATION_ID, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var bUSINESS_NAMEParameter = bUSINESS_NAME != null ?
                new ObjectParameter("BUSINESS_NAME", bUSINESS_NAME) :
                new ObjectParameter("BUSINESS_NAME", typeof(string));
    
            var bUSINESS_ADDRESSParameter = bUSINESS_ADDRESS != null ?
                new ObjectParameter("BUSINESS_ADDRESS", bUSINESS_ADDRESS) :
                new ObjectParameter("BUSINESS_ADDRESS", typeof(string));
    
            var bUSINESS_TYPEParameter = bUSINESS_TYPE != null ?
                new ObjectParameter("BUSINESS_TYPE", bUSINESS_TYPE) :
                new ObjectParameter("BUSINESS_TYPE", typeof(string));
    
            var rEG_NOParameter = rEG_NO != null ?
                new ObjectParameter("REG_NO", rEG_NO) :
                new ObjectParameter("REG_NO", typeof(string));
    
            var oWNER_NAMEParameter = oWNER_NAME != null ?
                new ObjectParameter("OWNER_NAME", oWNER_NAME) :
                new ObjectParameter("OWNER_NAME", typeof(string));
    
            var lOCATION_IDParameter = lOCATION_ID.HasValue ?
                new ObjectParameter("LOCATION_ID", lOCATION_ID) :
                new ObjectParameter("LOCATION_ID", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_BUSINESS", bUSINESS_NAMEParameter, bUSINESS_ADDRESSParameter, bUSINESS_TYPEParameter, rEG_NOParameter, oWNER_NAMEParameter, lOCATION_IDParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_CUST(string cUST_NAME, string eMAIL, string pHONE, string cUST_ADDRESS, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var cUST_NAMEParameter = cUST_NAME != null ?
                new ObjectParameter("CUST_NAME", cUST_NAME) :
                new ObjectParameter("CUST_NAME", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pHONEParameter = pHONE != null ?
                new ObjectParameter("PHONE", pHONE) :
                new ObjectParameter("PHONE", typeof(string));
    
            var cUST_ADDRESSParameter = cUST_ADDRESS != null ?
                new ObjectParameter("CUST_ADDRESS", cUST_ADDRESS) :
                new ObjectParameter("CUST_ADDRESS", typeof(string));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_CUST", cUST_NAMEParameter, eMAILParameter, pHONEParameter, cUST_ADDRESSParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_CUST_ORDERS(Nullable<System.DateTime> sCHEDULE_DATE, Nullable<System.TimeSpan> tIME_FROM, Nullable<System.TimeSpan> tIME_TO, Nullable<int> cUSTOMER_ID, Nullable<int> sERVICE_ID, Nullable<int> eMP_ID, Nullable<int> lOCATION_ID, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var sCHEDULE_DATEParameter = sCHEDULE_DATE.HasValue ?
                new ObjectParameter("SCHEDULE_DATE", sCHEDULE_DATE) :
                new ObjectParameter("SCHEDULE_DATE", typeof(System.DateTime));
    
            var tIME_FROMParameter = tIME_FROM.HasValue ?
                new ObjectParameter("TIME_FROM", tIME_FROM) :
                new ObjectParameter("TIME_FROM", typeof(System.TimeSpan));
    
            var tIME_TOParameter = tIME_TO.HasValue ?
                new ObjectParameter("TIME_TO", tIME_TO) :
                new ObjectParameter("TIME_TO", typeof(System.TimeSpan));
    
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            var sERVICE_IDParameter = sERVICE_ID.HasValue ?
                new ObjectParameter("SERVICE_ID", sERVICE_ID) :
                new ObjectParameter("SERVICE_ID", typeof(int));
    
            var eMP_IDParameter = eMP_ID.HasValue ?
                new ObjectParameter("EMP_ID", eMP_ID) :
                new ObjectParameter("EMP_ID", typeof(int));
    
            var lOCATION_IDParameter = lOCATION_ID.HasValue ?
                new ObjectParameter("LOCATION_ID", lOCATION_ID) :
                new ObjectParameter("LOCATION_ID", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_CUST_ORDERS", sCHEDULE_DATEParameter, tIME_FROMParameter, tIME_TOParameter, cUSTOMER_IDParameter, sERVICE_IDParameter, eMP_IDParameter, lOCATION_IDParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_EMPLOYEE(string eMP_NAME, string dEPARTMENT, Nullable<System.DateTime> dOJ, Nullable<int> gENDER, Nullable<int> lOCATION_ID, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var eMP_NAMEParameter = eMP_NAME != null ?
                new ObjectParameter("EMP_NAME", eMP_NAME) :
                new ObjectParameter("EMP_NAME", typeof(string));
    
            var dEPARTMENTParameter = dEPARTMENT != null ?
                new ObjectParameter("DEPARTMENT", dEPARTMENT) :
                new ObjectParameter("DEPARTMENT", typeof(string));
    
            var dOJParameter = dOJ.HasValue ?
                new ObjectParameter("DOJ", dOJ) :
                new ObjectParameter("DOJ", typeof(System.DateTime));
    
            var gENDERParameter = gENDER.HasValue ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(int));
    
            var lOCATION_IDParameter = lOCATION_ID.HasValue ?
                new ObjectParameter("LOCATION_ID", lOCATION_ID) :
                new ObjectParameter("LOCATION_ID", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_EMPLOYEE", eMP_NAMEParameter, dEPARTMENTParameter, dOJParameter, gENDERParameter, lOCATION_IDParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_LOCATION(string lOCATION_NAME, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var lOCATION_NAMEParameter = lOCATION_NAME != null ?
                new ObjectParameter("LOCATION_NAME", lOCATION_NAME) :
                new ObjectParameter("LOCATION_NAME", typeof(string));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_LOCATION", lOCATION_NAMEParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_PAYMENT(Nullable<int> oRDER_ID, Nullable<int> pAY_DETAILS, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var oRDER_IDParameter = oRDER_ID.HasValue ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(int));
    
            var pAY_DETAILSParameter = pAY_DETAILS.HasValue ?
                new ObjectParameter("PAY_DETAILS", pAY_DETAILS) :
                new ObjectParameter("PAY_DETAILS", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_PAYMENT", oRDER_IDParameter, pAY_DETAILSParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_SERVICES(string sERVICE_NAME, Nullable<decimal> rATE_PER_UNIT, Nullable<decimal> qUANTITY, Nullable<int> dURATION, Nullable<int> dURATION_TYPE, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var sERVICE_NAMEParameter = sERVICE_NAME != null ?
                new ObjectParameter("SERVICE_NAME", sERVICE_NAME) :
                new ObjectParameter("SERVICE_NAME", typeof(string));
    
            var rATE_PER_UNITParameter = rATE_PER_UNIT.HasValue ?
                new ObjectParameter("RATE_PER_UNIT", rATE_PER_UNIT) :
                new ObjectParameter("RATE_PER_UNIT", typeof(decimal));
    
            var qUANTITYParameter = qUANTITY.HasValue ?
                new ObjectParameter("QUANTITY", qUANTITY) :
                new ObjectParameter("QUANTITY", typeof(decimal));
    
            var dURATIONParameter = dURATION.HasValue ?
                new ObjectParameter("DURATION", dURATION) :
                new ObjectParameter("DURATION", typeof(int));
    
            var dURATION_TYPEParameter = dURATION_TYPE.HasValue ?
                new ObjectParameter("DURATION_TYPE", dURATION_TYPE) :
                new ObjectParameter("DURATION_TYPE", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_SERVICES", sERVICE_NAMEParameter, rATE_PER_UNITParameter, qUANTITYParameter, dURATIONParameter, dURATION_TYPEParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_X_SERVICE_EMPLOYEE(Nullable<int> sERVICE_ID, Nullable<int> eMP_ID, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var sERVICE_IDParameter = sERVICE_ID.HasValue ?
                new ObjectParameter("SERVICE_ID", sERVICE_ID) :
                new ObjectParameter("SERVICE_ID", typeof(int));
    
            var eMP_IDParameter = eMP_ID.HasValue ?
                new ObjectParameter("EMP_ID", eMP_ID) :
                new ObjectParameter("EMP_ID", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_X_SERVICE_EMPLOYEE", sERVICE_IDParameter, eMP_IDParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    
        public virtual int USP_INSERT_X_SERVICE_LOCATION(Nullable<int> lOCATION_ID, Nullable<int> sERVICE_ID, Nullable<System.DateTime> cREATED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<int> cREATED_BY_ID, Nullable<int> mODIFIED_BY_ID)
        {
            var lOCATION_IDParameter = lOCATION_ID.HasValue ?
                new ObjectParameter("LOCATION_ID", lOCATION_ID) :
                new ObjectParameter("LOCATION_ID", typeof(int));
    
            var sERVICE_IDParameter = sERVICE_ID.HasValue ?
                new ObjectParameter("SERVICE_ID", sERVICE_ID) :
                new ObjectParameter("SERVICE_ID", typeof(int));
    
            var cREATED_DATEParameter = cREATED_DATE.HasValue ?
                new ObjectParameter("CREATED_DATE", cREATED_DATE) :
                new ObjectParameter("CREATED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var cREATED_BY_IDParameter = cREATED_BY_ID.HasValue ?
                new ObjectParameter("CREATED_BY_ID", cREATED_BY_ID) :
                new ObjectParameter("CREATED_BY_ID", typeof(int));
    
            var mODIFIED_BY_IDParameter = mODIFIED_BY_ID.HasValue ?
                new ObjectParameter("MODIFIED_BY_ID", mODIFIED_BY_ID) :
                new ObjectParameter("MODIFIED_BY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_X_SERVICE_LOCATION", lOCATION_IDParameter, sERVICE_IDParameter, cREATED_DATEParameter, mODIFIED_DATEParameter, cREATED_BY_IDParameter, mODIFIED_BY_IDParameter);
        }
    }
}
