//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CUSTOMER()
        {
            this.TBL_CUST_ORDER = new HashSet<TBL_CUST_ORDER>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CUST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string CUST_ADDRESS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<int> MODIFIED_BY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CUST_ORDER> TBL_CUST_ORDER { get; set; }
    }
}
