//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUST_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CUST_ORDER()
        {
            this.TBL_PAYMENT = new HashSet<TBL_PAYMENT>();
        }
    
        public int CUST_ORDER_ID { get; set; }
        public Nullable<System.DateTime> SCHEDULE_DATE { get; set; }
        public Nullable<System.TimeSpan> TIME_FROM { get; set; }
        public Nullable<System.TimeSpan> TIME_TO { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<int> MODIFIED_BY_ID { get; set; }
    
        public virtual TBL_CUSTOMER TBL_CUSTOMER { get; set; }
        public virtual TBL_EMPLOYEE TBL_EMPLOYEE { get; set; }
        public virtual TBL_LOCATION TBL_LOCATION { get; set; }
        public virtual TBL_SERVICES TBL_SERVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PAYMENT> TBL_PAYMENT { get; set; }
    }
}
