//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SERVICE_CATEGORIES
    {
        public int SERVICE_CATEGORY_ID { get; set; }
        public string CATEGORY_TITLE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<int> MODIFIED_BY_ID { get; set; }
    }
}
