//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EMPLOYEE()
        {
            this.TBL_CUST_ORDER = new HashSet<TBL_CUST_ORDER>();
            this.X_SERVICE_EMPLOYEE = new HashSet<X_SERVICE_EMPLOYEE>();
        }
    
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<int> MODIFIED_BY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CUST_ORDER> TBL_CUST_ORDER { get; set; }
        public virtual TBL_LOCATION TBL_LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<X_SERVICE_EMPLOYEE> X_SERVICE_EMPLOYEE { get; set; }
    }
}
