//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BUSINESS
    {
        public int BUSINESS_ID { get; set; }
        public string BUSINESS_NAME { get; set; }
        public string BUSINESS_ADDRESS { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string REG_NO { get; set; }
        public string OWNER_NAME { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<int> MODIFIED_BY_ID { get; set; }
    
        public virtual TBL_LOCATION TBL_LOCATION { get; set; }
    }
}
