//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_SERVICE_LOCATION
    {
        public int X_SERVICE_LOCATION_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<int> MODIFIED_BY_ID { get; set; }
    
        public virtual TBL_LOCATION TBL_LOCATION { get; set; }
        public virtual TBL_SERVICES TBL_SERVICES { get; set; }
    }
}
